### ISSUE TITLE
Sidebar to read top to bottom or bottom to top?

### ISSUE THREAD

**Issue by alan-mj-lin** [alan-mj-lin/Mafia#16]
It just seems like a more user friendly UI if it reads top to bottom and have it auto-scroll to the bottom so they always see error messages for invalid actions.

**Comment by hchiam** [comment]
We can make the error message `display:sticky` or `display:fixed` for now, and then at the same time maybe put the other messages in a custom component that I can style with custom CSS to do the auto scroll for you. Unless you want to research some react library or component that does what we want for the non-error messages

**Comment by hchiam** [comment]
https://material-ui.com/components/snackbars/

**Comment by hchiam** [comment]
@alan-mj-lin we still should figure out that auto-scroll thing for the sidebar messages. When the game has a few rounds, the messages start to go off-screen.

**Comment by alan-mj-lin** [comment]
closing
